import React, { useCallback, useState } from 'react';
import { Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { api } from '../lib/api';
import { useAuth } from '../lib/auth';
import LiveTrackingMap, { TrackingMarker } from '../components/LiveTrackingMap';
import { Screen } from '../lib/Screen';
import { theme } from '../theme';

const CONTACTS = ['National emergency · 112', 'Police · 100', 'Ambulance · 108', 'Tourist helpline (India) · 1363'];

export default function AdminScreen() {
  const { user, signOut } = useAuth();
  const [data, setData] = useState<any>({ alerts: [], liveTourists: [], liveGuides: [], trips: [] });
  const [refreshing, setRefreshing] = useState(false);
  const load = async () => { try { setRefreshing(true); setData(await api('/api/admin/overview')); } catch (e: any) { Alert.alert('Control room unavailable', e.message); } finally { setRefreshing(false); } };
  useFocusEffect(useCallback(() => { load(); const poll = setInterval(load, 10000); return () => clearInterval(poll); }, []));
  const markers: TrackingMarker[] = [...(data.liveTourists || []).map((p: any) => ({ id: `t-${p.userId}`, latitude: p.latitude, longitude: p.longitude, title: `Traveller: ${p.name}`, color: '#1a7fe0' })), ...(data.liveGuides || []).map((p: any) => ({ id: `g-${p.guideId}`, latitude: p.latitude, longitude: p.longitude, title: `Guide: ${p.guide?.user?.name || 'Guide'}`, color: '#ed5b43' }))];
  const resolve = async (id: string) => { try { await api(`/api/admin/alerts/${id}/resolve`, { method: 'PUT' }); load(); } catch (e: any) { Alert.alert('Could not resolve SOS', e.message); } };
  return <Screen><Text style={s.h1}>Safety control room</Text><Text style={s.sub}>{user?.name} · Administrator</Text><FlatList data={data.alerts || []} keyExtractor={(x) => x.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load} />} contentContainerStyle={{ paddingBottom: 40 }} ListHeaderComponent={<><View style={s.card}><Text style={s.h}>Emergency contacts</Text>{CONTACTS.map((c) => <Text key={c} style={s.line}>{c}</Text>)}</View><View style={s.card}><Text style={s.h}>Live traveller & guide tracking</Text><Text style={s.muted}>{data.liveTourists?.length || 0} traveller(s) · {data.liveGuides?.length || 0} guide(s) sharing GPS</Text><LiveTrackingMap markers={markers} /><Text style={s.legend}>Blue: traveller   Orange: guide</Text></View><View style={s.card}><Text style={s.h}>Trips taken up by users</Text>{(data.trips || []).length ? data.trips.map((t: any) => <View key={t.id} style={s.row}><Text style={s.rowH}>{t.tourist?.name || 'Traveller'} · {t.spot?.name || 'Trip'}</Text><Text style={s.muted}>{String(t.startDate).slice(0, 10)} → {String(t.endDate).slice(0, 10)} · {t.status}</Text></View>) : <Text style={s.muted}>No trips recorded yet.</Text>}</View><Text style={s.section}>Active SOS messages</Text></>} renderItem={({ item }) => <View style={s.alert}><Text style={s.rowH}>SOS · {item.user?.name || 'Traveller'}</Text><Text style={s.muted}>{item.user?.email || ''}</Text>{item.message ? <Text style={s.message}>{item.message}</Text> : null}{item.latitude != null ? <Text style={s.muted}>GPS: {Number(item.latitude).toFixed(4)}, {Number(item.longitude).toFixed(4)}</Text> : null}<Pressable style={s.resolve} onPress={() => resolve(item.id)}><Text style={s.resolveT}>Mark resolved</Text></Pressable></View>} ListEmptyComponent={<Text style={s.muted}>No active SOS messages.</Text>} ListFooterComponent={<Pressable style={s.signout} onPress={signOut}><Text style={s.signoutT}>Sign out</Text></Pressable>} /></Screen>;
}

const s = StyleSheet.create({ h1: { fontSize: 22, fontWeight: '800', color: theme.ink }, sub: { color: theme.muted, marginTop: 3 }, card: { backgroundColor: '#fff', borderWidth: 1, borderColor: theme.line, borderRadius: 14, padding: 14, marginTop: 12 }, h: { fontSize: 15, fontWeight: '800', color: theme.tealDark }, line: { marginTop: 6, color: theme.ink, fontSize: 13 }, muted: { color: theme.muted, fontSize: 12, marginTop: 5 }, legend: { color: theme.muted, fontSize: 11, marginTop: 8 }, section: { fontSize: 16, fontWeight: '800', color: theme.ink, marginTop: 16 }, row: { borderTopWidth: 1, borderTopColor: theme.line, marginTop: 8, paddingTop: 8 }, rowH: { color: theme.ink, fontSize: 13, fontWeight: '800' }, alert: { backgroundColor: '#fff', borderRadius: 12, padding: 13, marginTop: 8, borderWidth: 1, borderColor: '#f0c6c1' }, message: { color: theme.ink, marginTop: 7 }, resolve: { backgroundColor: theme.teal, borderRadius: 9, padding: 10, alignItems: 'center', marginTop: 10 }, resolveT: { color: '#fff', fontWeight: '800', fontSize: 12 }, signout: { borderWidth: 1, borderColor: theme.line, borderRadius: 10, padding: 12, alignItems: 'center', marginTop: 20 }, signoutT: { color: theme.danger, fontWeight: '800' } });
