require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const { PrismaClient } = require('@prisma/client');
const auth = require('./middleware/auth');
const routes = require('./routes');
const path = require('path');

const app = express();
const prisma = new PrismaClient();
app.set('prisma', prisma);
app.use(helmet({ contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'", "'unsafe-inline'", 'https://unpkg.com'], styleSrc: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com', 'https://unpkg.com'], fontSrc: ["'self'", 'https://fonts.gstatic.com'], imgSrc: ["'self'", 'data:', 'https:'], connectSrc: ["'self'", 'https:'], workerSrc: ["'self'", 'blob:'] } } }));
app.use(cors({ origin: process.env.CLIENT_ORIGIN?.split(',') || true }));
app.use(express.json({ limit: '1mb' }));
app.use(morgan('dev'));
app.use(express.static(path.join(__dirname, '..')));
app.get('/health', (_, res) => res.json({ status: 'ok', service: 'yatrasetu-api' }));
app.use('/api/auth', routes.auth);
app.use('/api/spots', routes.spots);
app.use('/api/trips', auth, routes.trips);
app.use('/api/verify', auth, routes.verify);
app.use('/api/admin', auth, routes.admin);
app.use('/api/location', auth, routes.location);
app.use('/api/requests', auth, routes.requests);
app.use('/api/safety', auth, routes.safety);
app.use('/api/feedback', auth, routes.feedback);
app.use((err, _, res, __) => { console.error(err); res.status(err.status || 500).json({ error: err.message || 'Internal server error' }); });
const port = Number(process.env.PORT || 4000);
app.listen(port, () => console.log(`YatraSetu API listening on http://localhost:${port}`));
